         "EOF expected",
         "identifie expected",
         "numbe expected",
         "hexnumbe expected",
         "sting1 expected",
         "cha1 expected",
         "libay expected",
         "\"use\" expected",
         "\";\" expected",
         "\"load\" expected",
         "\"=\" expected",
         "\"inheit\" expected",
         "\"class\" expected",
         "\"{\" expected",
         "\"}\" expected",
         "\"static\" expected",
         "\"my\" expected",
         "\"function\" expected",
         "\"va\" expected",
         "\"mixed\" expected",
         "\"shot\" expected",
         "\"int\" expected",
         "\"long\" expected",
         "\"float\" expected",
         "\"unsigned\" expected",
         "\"cha\" expected",
         "\"double\" expected",
         "\"void\" expected",
         "\"sting\" expected",
         "\",\" expected",
         "\"[\" expected",
         "\"]\" expected",
         "\"(\" expected",
         "\")\" expected",
         "\"*\" expected",
         "\"case\" expected",
         "\":\" expected",
         "\"default\" expected",
         "\"beak\" expected",
         "\"continue\" expected",
         "\"do\" expected",
         "\"while\" expected",
         "\"fo\" expected",
         "\"if\" expected",
         "\"else\" expected",
         "\"etun\" expected",
         "\"switch\" expected",
         "\"||\" expected",
         "\"&&\" expected",
         "\"|\" expected",
         "\"^\" expected",
         "\"&\" expected",
         "\"==\" expected",
         "\"!=\" expected",
         "\"<\" expected",
         "\">\" expected",
         "\"<=\" expected",
         "\">=\" expected",
         "\"<<\" expected",
         "\">>\" expected",
         "\"+\" expected",
         "\"-\" expected",
         "\"/\" expected",
         "\"%\" expected",
         "\"++\" expected",
         "\"--\" expected",
         "\".\" expected",
         "\"->\" expected",
         "\"::\" expected",
         "\"new\" expected",
         "\"*=\" expected",
         "\"/=\" expected",
         "\"%=\" expected",
         "\"+=\" expected",
         "\"-=\" expected",
         "\"&=\" expected",
         "\"^=\" expected",
         "\"|=\" expected",
         "\"<<=\" expected",
         "\">>=\" expected",
         "\"!\" expected",
         "\"~\" expected",
         "not expected",
         "PePocesso expected",
         "unexpected symbol in C",
         "unexpected symbol in Definition",
         "unexpected symbol in Definition",
         "unexpected symbol in Definition",
         "unexpected symbol in StoageClass",
         "unexpected symbol in Type",
         "unexpected symbol in Type",
         "unexpected symbol in Type",
         "unexpected symbol in Type",
         "unexpected symbol in CompoundStatement",
         "unexpected symbol in Statement",
         "unexpected symbol in Label",
         "unexpected symbol in LocalDeclaation",
         "unexpected symbol in AssignmentOpeato",
         "unexpected symbol in EqualExp",
         "unexpected symbol in RelationExp",
         "unexpected symbol in ShiftExp",
         "unexpected symbol in AddExp",
         "unexpected symbol in MultExp",
         "unexpected symbol in UnayExp",
         "unexpected symbol in UnayExp",
         "unexpected symbol in PostFixExp",
         "unexpected symbol in UnayOpeato",
         "unexpected symbol in Pimay",
         "unexpected symbol in HashItem",
         "unexpected symbol in SetItem",
