#define EOF_Sym	0	/* EOF */
#define identifierSym	1	/* identifier */
#define numberSym	2	/* number */
#define hexnumberSym	3	/* hexnumber */
#define stringD1Sym	4	/* string1 */
#define charSym	5	/* char */
#define librarySym	6	/* library */
#define StarSym	7	/* "*" */
#define SemicolonSym	8	/* ";" */
#define inheritSym	9	/* "inherit" */
#define classSym	10	/* "class" */
#define LbraceSym	11	/* "{" */
#define RbraceSym	12	/* "}" */
#define autoSym	13	/* "auto" */
#define externSym	14	/* "extern" */
#define registerSym	15	/* "register" */
#define staticSym	16	/* "static" */
#define shortSym	17	/* "short" */
#define intSym	18	/* "int" */
#define longSym	19	/* "long" */
#define floatSym	20	/* "float" */
#define unsignedSym	21	/* "unsigned" */
#define charSym	22	/* "char" */
#define doubleSym	23	/* "double" */
#define voidSym	24	/* "void" */
#define stringSym	25	/* "string" */
#define CommaSym	26	/* "," */
#define LbrackSym	27	/* "[" */
#define RbrackSym	28	/* "]" */
#define LparenSym	29	/* "(" */
#define RparenSym	30	/* ")" */
#define caseSym	31	/* "case" */
#define ColonSym	32	/* ":" */
#define defaultSym	33	/* "default" */
#define breakSym	34	/* "break" */
#define continueSym	35	/* "continue" */
#define doSym	36	/* "do" */
#define whileSym	37	/* "while" */
#define forSym	38	/* "for" */
#define ifSym	39	/* "if" */
#define elseSym	40	/* "else" */
#define returnSym	41	/* "return" */
#define switchSym	42	/* "switch" */
#define BarBarSym	43	/* "||" */
#define AndAndSym	44	/* "&&" */
#define BarSym	45	/* "|" */
#define UparrowSym	46	/* "^" */
#define AndSym	47	/* "&" */
#define EqualEqualSym	48	/* "==" */
#define BangEqualSym	49	/* "!=" */
#define LessSym	50	/* "<" */
#define GreaterSym	51	/* ">" */
#define LessEqualSym	52	/* "<=" */
#define GreaterEqualSym	53	/* ">=" */
#define LessLessSym	54	/* "<<" */
#define GreaterGreaterSym	55	/* ">>" */
#define PlusSym	56	/* "+" */
#define MinusSym	57	/* "-" */
#define SlashSym	58	/* "/" */
#define PercentSym	59	/* "%" */
#define PlusPlusSym	60	/* "++" */
#define MinusMinusSym	61	/* "--" */
#define PointSym	62	/* "." */
#define MinusGreaterSym	63	/* "->" */
#define EqualSym	64	/* "=" */
#define StarEqualSym	65	/* "*=" */
#define SlashEqualSym	66	/* "/=" */
#define PercentEqualSym	67	/* "%=" */
#define PlusEqualSym	68	/* "+=" */
#define MinusEqualSym	69	/* "-=" */
#define AndEqualSym	70	/* "&=" */
#define UparrowEqualSym	71	/* "^=" */
#define BarEqualSym	72	/* "|=" */
#define LessLessEqualSym	73	/* "<<=" */
#define GreaterGreaterEqualSym	74	/* ">>=" */
#define BangSym	75	/* "!" */
#define TildeSym	76	/* "~" */
#define No_Sym	77	/* not */
#define PreProcessorSym	78	/* PreProcessor */
#define MAXT	No_Sym	/* Max Terminals */
